---

- name: EC2インスタンスを作成
  ec2:
    image: "{{ ami_image }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    group: "{{ group_name }}"
    instance_tags:
      Name: "{{ group_name }}"
    exact_count: 1
    count_tag:
      Name: "{{ group_name }}"
    wait: yes
    wait_timeout: 300
    volumes:
      - device_name: "{{ device_name }}"
        volume_type: "{{ volume_type }}"
        volume_size: "{{ volume_size }}"
        delete_on_termination: yes
    instance_profile_name: ap_servers
  register: ec2

- name: SSHで接続できるようになるまで待機
  wait_for: port=22 host="{{ item.public_ip }}" timeout=300 state=started
  with_items: ec2.instances

- name: 作成したEC2インスタンスをインベントリに追加
  add_host: hostname="{{ item.public_ip }}" groupname="tag_Name_{{ group_name }}"
  with_items: ec2.instances
