---

- name: AWSリソースのセットアップ
  hosts: localhost
  connection: local
  roles:
    - ec2
    - elasticache
    - rds
    - s3
  vars:
    service_name: nslides01
    group_name: application
    region: ap-northeast-1

- name: アプリケーションサーバーのセットアップ
  hosts: tag_Name_application
  remote_user: ec2-user
  become: yes
  roles:
    - sudo
    - nginx
    - mysql
    - ruby
    - panel_base
  vars:
    db_host:    "{{ groups.rds[0] }}"
    redis_host: "{{ groups.elasticache_redis[0] }}"

- hosts: tag_Name_application
  remote_user: ec2-user
  become: no
  roles:
