---

- yum: name={{item}} state=latest
  with_items:
    - nginx

- name: create nginx.conf
  copy:
    src: roles/nginx/files/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: create setting directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: change log_dir permission
  become: yes
  file:
    path: /var/log/nginx
    state: directory
    owner: nginx
    group: nginx
    mode: 0755

- name: service登録
  service:
    name: nginx
    state: started
    enabled: yes

