---

- name: RDS用セキュリティグループを作成
  ec2_group:
    name: rds
    description: rds
    region: ap-northeast-1
    rules:
      - proto: tcp
        from_port: 3306
        to_port:   3306
        group_name: "{{ group_name }}"
    rules_egress:
      - proto: all
        from_port: 0
        to_port:   65535
        cidr_ip:   0.0.0.0/0

- name: RDSインスタンスを作成
  rds:
    command: create
    instance_name: "{{ service_name }}"
    db_engine: MySQL
    size: 20
    instance_type: db.t2.micro
    region: "{{ region }}"
    multi_zone: no
    username: "{{ db_username }}"
    password: "{{ db_password }}"
    wait: yes
    wait_timeout: 300
    security_groups: rds
  register: rds

- name: 作成したRDSインスタンスのエンドポイント
  debug: msg="The new db endpoint is {{ rds.instance.endpoint }}"
