---

# http://qiita.com/nagi244/items/cccf5cfc6d17d41186fd

# mysql install
- name: install mysql
  yum: name=http://ftp.jaist.ac.jp/pub/mysql/Downloads/MySQL-5.6/{{ item.rpm }} state=present
  with_items:
    - rpm: MySQL-client-5.6.28-1.el6.x86_64.rpm
    - rpm: MySQL-shared-compat-5.6.28-1.el6.x86_64.rpm
    - rpm: MySQL-shared-5.6.28-1.el6.x86_64.rpm
    - rpm: MySQL-devel-5.6.28-1.el6.x86_64.rpm
    - rpm: MySQL-server-5.6.28-1.el6.x86_64.rpm
  tags: mysql

# mysqld自動起動設定
- name: be sure mysqld is running and enabled
  service: name=mysql state=running enabled=yes
  tags: mysql
