---

- name: ElastiCache用セキュリティグループを作成
  ec2_group:
    name: redis
    description: redis
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 6379
        to_port:   6379
        group_name: "{{ group_name }}"
    rules_egress:
      - proto: all
        from_port: 0
        to_port:   65535
        cidr_ip:   0.0.0.0/0
  register: sg

- name: AWS ElastiCacheのセットアップ
  elasticache:
    name: "{{ service_name }}"
    state: present
    engine: redis
    cache_engine_version: 2.8.24
    node_type: "{{ node_type }}"
    num_nodes: 1
    cache_port: 6379
    cache_security_groups: []
    security_group_ids:
      - "{{ sg.group_id }}"
    region: "{{ region }}"
    zone: ap-northeast-1a
  register: result

- name: 作成したElastiCacheのエンドポイント
  debug: msg="The new ElastiCache endpoint is {{ result.elasticache.data.CacheNodes[0].Endpoint }}"
